config/routes.rb
Terminarz::Application.routes.draw do
  
  devise_for :users

  match '/changelog', to: 'static_pages#changelog'

  match '/leave', to: 'static_pages#leave'

  root to: 'tasks#index'
  resources :tasks do
    member do
      post 'toggle'
    end
  end

end

app/models/task.rb
# encoding: utf-8

# == Schema Information
#
# Table name: tasks
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  done       :boolean         default(FALSE)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  user_id    :integer
#

class Task < ActiveRecord::Base
  attr_accessible :date, :done, :name, :task_dates, :task_dates_attributes 
 
  has_many :task_dates, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :task_dates, :allow_destroy => true

  validates :name,  :presence => true
  validate :date_existence, :date_uniqueness

  after_validation :unmark_for_destruction

  # reset marked_for_destroy option of dates
  # after failed date_existence validation
  def unmark_for_destruction
    if self.errors.has_key?(:base)
      task_dates.each { |t| t.reload if t.marked_for_destruction? }
    end
  end

  def date_existence
    # require minimum one date
    errors.add :base, 'Musisz podać przynajmniej 1 datę' if task_dates.all?(&:marked_for_destruction?)
  end

  def date_uniqueness
    errors.add :base, 'Daty nie mogą być duplikatami' unless task_dates.map(&:date).uniq.size == task_dates.size
  end
end

app/models/task_date.rb
# == Schema Information
#
# Table name: task_dates
#
#  id         :integer         not null, primary key
#  date       :date
#  task_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class TaskDate < ActiveRecord::Base
  attr_accessible :date, :task_id

  belongs_to :task 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  settings               :text(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  # store field for leave value
  store :settings, accessors: [:leave_all, :leave_used, :leave_days]
  # call method to set default value of leave after creation of new user
  after_initialize :initialize_defaults, :if => :new_record?


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :tasks, :dependent => :destroy

  private
    # set default value of leave
    def initialize_defaults
      self.leave_all = 0 if self.leave_all.nil?
      self.leave_used = 0 if self.leave_used.nil?
      self.leave_days = '' if self.leave_days.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, :except => :changelog

  def leave
    @leave_days = current_user.leave_days

    @days_selected = params[:daysSelected]
    @days_used = params[:daysSelectedCount]

    days_all = params[:daysAll]

    if !days_all.nil?
      current_user.leave_all = days_all
      current_user.save
    end

    if !@days_selected.nil?
      current_user.leave_used = @days_used
      current_user.leave_days = @days_selected
      current_user.save
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def changelog
  end
end

app/controllers/tasks_controller.rb
# encoding: utf-8

class TasksController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /tasks
  def index
    # @tasks = Task.order("date")

    @tasks_done = current_user.tasks.where(:done => true)
    # add sorting date
    @tasks_not_done = current_user.tasks.where(:done => false)
  end

  # GET /tasks/1
  def show
    @task = current_user.tasks.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.new(:task_dates => [TaskDate.new])
    @update_button_text = "Utwórz zadanie"
  end

  # GET /tasks/1/edit
  def edit
    @task = current_user.tasks.find(params[:id])
    @update_button_text = "Aktualizuj zadanie"

  end

  # POST /tasks
  def create
    @task = current_user.tasks.new(params[:task])

    if @task.save
      redirect_to @task, notice: 'Zadanie zostało utworzone.'
    else
      render action: "new"
    end
  end

  # PUT /tasks/1
  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to @task, notice: 'Zadanie zostało uaktualnone.'

    else
      render action: "edit"
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    redirect_to tasks_url
  end

  # YES/NO button switcher
  def toggle
    @task = current_user.tasks.find(params[:id])
    @task.toggle!(:done)

    # to do order by date
    @tasks_done = current_user.tasks.where(:done => true)
    @tasks_not_done = current_user.tasks.where(:done => false)

    respond_to do |format|
      format.js
      format.html { render :nothing => true }
    end
  end
end

app/helpers/application_helper.rb
# encoding: utf-8

module ApplicationHelper
  def link_to_add_dates(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render("form_dates", :f => builder)
    end
    link_to name, '#', :class => 'add_date', :data => { :id => id, :fields => fields.gsub("\n", "") }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def date_diff(date)
    (date - Date.today).to_i
  end

  # bootstrap's progress bar color
  def progress_class(value)
    color_class = case value
                  when 0...15 then "progress-danger"
                  when 15...33 then "progress-warning"
                  else "progress-success"
                  end
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Terminarz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="navbar">
  <div class="navbar-inner">
    <div class="container" id="nav_container">
      <%= link_to "Terminarz", root_path, class: "brand" %>
      <ul class="nav nav-tabs">
        <li><%= link_to "Zadania", root_path %></li>
        <li><%= link_to "Urlop", leave_path %></li>
        <li><%= link_to "Changelog", changelog_path %></li>
      </ul>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to 'Wyloguj', destroy_user_session_path, method: :delete %>        
          </li>
        <% else %>
          <li>
          <%= link_to 'Zaloguj się', new_user_session_path %>  
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li>
          <%= link_to 'Edycja konta', edit_user_registration_path %>
          </li>
        <% else %>
          <li>
          <%= link_to 'Rejestracja', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div id="content">
<%= render 'layouts/messages' %>
<%= yield %>
</div>
</body>
</html>

app/views/static_pages/changelog.html.erb
<h1>Changelog</h1>

<br />

<div class="well">
<strong>31.08.2012</strong>
<ul>
  <li>Konta użytkowników działają</li>
  <li>niezalogowany użytkownik może zobaczyć tylko niniejszą stronę, oraz strony logowania/rejestracji konta</li>
  <li>Zmiany w kalendarzu są zapisywane w bazie</li>
</ul>
</div>

<div class="well">
<strong>30.08.2012</strong>
<ul>
  <li>Dodano kalendarz do strony z urlopem</li>
</ul>
</div>

<div class="well">
<strong>10.08.2012</strong>
<ul>
  <li>dodano ukrywanie/pokazywanie zadań wykonanych za pomocą przycisku</li>
</ul>
</div>

<div class="well">
<strong>08.08.2012</strong>
<ul>
  <li>podział zadań na wykonane/niewykonane, kliknięcie na przycisk TAK/NIE przenosi zad. do odpowiedniej części</li>
  <li>Zablokowana możliwość wpisania pustej nazwy zadania</li>
</ul>
</div>

<div class="well">
<strong>03.08.2012</strong>
<ul>
  <li>dodano nawigację u góry strony, oraz strony do urlopu i changelog (zmiany na stronie)</li>
</ul>
</div>

app/views/static_pages/leave.html.erb
<h1>Urlop</h1>

<div class="well" id="leave_wrapper">
  <div id="leave_all_left">Ilość dni urlopu/rok: 
    <span class="label label-info" id="leave_all_value"><%= current_user.leave_all %></span>
  </div>
  <div id="leave_all_right">
    <div id="leave_all_right_up"><i class="icon-chevron-up"></i></div>
    <div id="leave_all_right_down"><i class="icon-chevron-down"></i></div>
  </div>
      <%# <button class="btn btn-info btn-small" id="leave_submit">Zapisz zmiany</button> %>

  <div id="leave_left">Dni pozostało: 
    <span class="label label-info" id="leave_left_value">
      <%= Integer(current_user.leave_all) - Integer(current_user.leave_used) %>
    </span>
  </div>
  <div id="leave_used">Dni wykorzystanych: 
    <span class="label label-info" id="leave_used_value"><%= current_user.leave_used %></span>
  </div>
</div>


<%# rails' tag creates xml-like <div /> messing divs order %>
<%= content_tag :div, nil, :id => "calendar", :data => { :days => @leave_days } %>

app/views/static_pages/leave.js.coffee.erb
###
  for format.js in dev env one can use coffeescript with ERB preprocessing
  but leaving off '.erb'
  so leave.js.coffee is working
  but leave.js.coffee.erb is not O_o

  for deployment (heroku) Coffeescript is not working in view .js.coffee(.erb)

  'coffeebeans' gem solves both issues
###

$ ->
  $('#leave_used_value').html(<%= @days_used %>)

  leave_used_value = parseInt $('#leave_used_value').html()
  leave_all_value = parseInt $('#leave_all_value').html()
  leave_left_value = leave_all_value - leave_used_value

  $('#leave_left_value').html(leave_left_value)

app/views/tasks/_form.html.erb
<%= form_for(@task, html: { class: "well" }) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>Zadanie nie zostało zapisane z powodu
        <%= @task.errors.count > 1 ? " #{@task.errors.count} błędów:" : " błędu:" %>
      </h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nazwa zadania:" %>
    <%= f.text_field :name, class: "span4" %>
  </div>
  <div class="field">
    <%= f.fields_for :task_dates do |date| %>
      <%= render 'form_dates', :f => date %>
    <% end %>
    <%= link_to_add_dates 'Dodaj datę', f, :task_dates %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit @update_button_text, class: "btn btn-info" %>
  </div>
<% end %>

app/views/tasks/_form_dates.html.erb
<fieldset>
  <%= f.label :date, "Data:" %>
  <%= f.date_select :date, {}, { class: "span2" } %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Usuń", "#", class: "remove_date" %>
</fieldset>

app/views/tasks/_task_table.html.erb
<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Wykonano?</th>
    <th class='table-name'>Nazwa</th>
    <th>Dni pozostało</th>
    <th>Data</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% tasks.each do |task| %>
  <% diff = date_diff(task.task_dates[0].date) %>
  <tr>
    <td>
      <%= button_to task.done ? "TAK" : "NIE", 
              {},
              { id: task.id, class: 'btn btn-info yes-no' , :remote => true }  %>
    </td>
    <td><h1><span class="label label-success"><%= task.name %></span><h1></td>

     <td>
      <span id="days_left" class="label"><%= diff %></span>   
      <div class="progress <%= progress_class(diff) %>">
        <div class="bar" style="width: <%= diff %>%;"></div>
      </div>
      

    </td>
    <td><span class="label label-warning"><%= task.task_dates[0].date %></span></td>

    <td class='btn-group  table-operations'>
        <%= link_to "Pokaż", task, class: "btn btn-info" %>
        <%= link_to "Edytuj", edit_task_path(task), class: "btn btn-info" %>
        <%= link_to "Usuń", task, :data => { confirm: 'Jesteś pewien?' }, method: :delete,  class: "btn btn-danger" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

app/views/tasks/edit.html.erb
<h1>Edycja zadania</h1>

<br />
<%= render 'form' %>

<%= link_to 'Pokaż', @task %> |
<%= link_to 'Powrót', tasks_path %>

app/views/tasks/index.html.erb
<h1>Lista zadań</h1>
<br />

<h3><%= link_to 'Nowe zadanie', new_task_path %></h3>



<!-- poprawić kolejność -->
<span id="current_date" class="label label-warning"><%= Date.today %></span>
<span id="current_date_label" class="label label-warning current_date">Aktualna data:</span>

<div id="tasks_not_done_table">
<%= render partial: "task_table", locals: { :tasks => @tasks_not_done } %>
</div>

<button id="button-done" class="btn btn-info">Pokaż/Ukryj zadania wykonane</button>

<div id="tasks_done_table">
<%= render partial: "task_table", locals: { :tasks => @tasks_done } %>
</div>

<br />

<h3><%= link_to 'Nowe zadanie', new_task_path %></h3>

<br />

app/views/tasks/new.html.erb
<h1>Nowe zadanie</h1>

<%= render 'form' %>

<%= link_to 'Powrót', tasks_path %>

app/views/tasks/show.html.erb
<div class="well">
<p>
  <b>Nazwa zadania:</b>
  <%= @task.name %>
</p>

<p>
  <b>Czy wykonano?:</b>
  <%= @task.done ? "TAK" : "NIE" %>
</p>

<p>
  <b>Daty:</b><br />
  <% @task.task_dates.each do |date| %>
    <%= date.date %><br />
  <% end %>
</p>

<p>
  <b>Dni pozostało:</b>
  <%#date_diff(@task.date) %>
</p>
</div>
<br /><br />

<%= link_to 'Edytuj', edit_task_path(@task) %> |
<%= link_to 'Powrót', tasks_path %>

app/views/tasks/toggle.js.erb
$('#tasks_not_done_table').html("<%=j render partial: "task_table",  locals: { :tasks => @tasks_not_done } %>");
$('#tasks_done_table').html("<%=j render partial: "task_table", locals: { :tasks => @tasks_done } %>");

tasks_not_done_count = $('#tasks_done_table table tbody').children().length;

$('#button-done').html("Pokaż/Ukryj zadania wykonane (" + tasks_not_done_count + ")" );

// get <td> of recently clicked item, after re-rendering
td = $('#<%= @task.id %>').parent().parent().parent();

// get css <td> background-color of recently clicked item
color = td.css('background-color');

// animate bg color from green to proper table row color in 5s
td.parent().children().css({'background-color':'#114411'}).
  animate({'background-color':color}, 5000);